#!/bin/bash

# --- PATH RESOLUTION ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/layout.conf"
AUTOSTART_FILE="$(realpath "${SCRIPT_DIR}/../autostart.conf")"
LOG_FILE="${SCRIPT_DIR}/layout.log"

# --- CLEAN LOGGING ---
log() {
    local timestamp=$(date +'%H:%M:%S')
    echo "[${timestamp}] [$1] $2" | tee -a "${LOG_FILE}" >&2
}

# --- ENGINE UTILITIES ---
run_hypr() { hyprctl "$@" >> /dev/null 2>&1; }

# === THE FIX: CACHED JSON DATA ===
# Instead of querying the socket every time, we read from a global variable
get_window_data() {
    local class="$1" ws="$2"
    echo "$CLIENTS_CACHE" | jq -c ".[] | select((.class | contains(\"$class\")) and .workspace.id == $ws)" | head -n 1
}

get_monitor_data() {
    local ws="$1"
    local mon=$(echo "$MONITORS_CACHE" | jq -c ".[] | select(.activeWorkspace.id == $ws)" | head -n 1)
    [[ -z "$mon" ]] && mon=$(echo "$MONITORS_CACHE" | jq -c ".[0]")
    echo "$mon"
}

# --- INITIALIZATION ---
declare -A ALIAS_MAP CMD_MAP WS_MAP FOCUS_RULES

while read -r line; do
    [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "$line" ]] && continue
    read -ra args <<< "$line"
    case "${args[0]}" in
        "APP")
            ALIAS_MAP["${args[1]}"]="${args[2]}"
            CMD_MAP["${args[1]}"]="${args[*]:3}"
            ;;
        "RATIO"|"GROUP")
            for app in "${args[@]:2}"; do WS_MAP["$app"]="${args[1]}"; done
            ;;
        "FOCUS")
            if [[ "${args[1]}" =~ ^[0-9]+$ ]]; then
                FOCUS_RULES["${args[1]}"]="${args[2]}"
            else
                al="${args[1]}" # FIX 1: Removed 'local' keyword
                FOCUS_RULES["${WS_MAP[$al]:-1}"]="$al"
            fi
            ;;
    esac
done < "${CONFIG_FILE}"

# === THE MISSING GENERATOR ===
if [[ "$1" == "generate" || "$1" == "--generate" ]]; then
    log "INFO" "Generating $AUTOSTART_FILE..."
    
    # Write custom header
    echo "# Auto-generated by layout-engine for ${USER:-lanusri-}" > "${AUTOSTART_FILE}"
    echo "# Source: ${CONFIG_FILE}" >> "${AUTOSTART_FILE}"
    echo "" >> "${AUTOSTART_FILE}"

    for alias in "${!CMD_MAP[@]}"; do
        ws="${WS_MAP[$alias]}"
        cmd="${CMD_MAP[$alias]}"
        
        # Wrap the command with the uwsm app runner and cache check
        wrapped_cmd="sh -c '[ ! -f \$HOME/.cache/disable_autostart ] && uwsm app -- $cmd'"
        
        if [[ -n "$ws" ]]; then
            echo "exec-once = [workspace $ws silent] $wrapped_cmd" >> "${AUTOSTART_FILE}"
        else
            echo "exec-once = $wrapped_cmd" >> "${AUTOSTART_FILE}"
        fi
    done
    
    # Automatically append the layout engine daemon loop
    echo "exec-once = ${SCRIPT_DIR}/layout.sh --loop" >> "${AUTOSTART_FILE}"
    
    log "OK" "Generation complete. File saved to ${AUTOSTART_FILE}."
    exit 0
fi
# =============================

# --- THE REACTIVE CORE ---
process_rule() {
    local type="$1" ws="$2" alias="$3" addr="$4" args=("${@:5}")
    local rule_id="${ws}_${type}_${alias}"

    [[ -n "${PROCESSED_RULES[$rule_id]}" ]] && return

    local mon_json=$(get_monitor_data "$ws")
    local mon_w=$(echo "$mon_json" | jq -r '.width')
    local mon_x=$(echo "$mon_json" | jq -r '.x')
    local master_threshold=$((mon_x + 100))

    case "$type" in
        "RATIO")
            local move_dir="${args[0]}"
            local x_pct=$(echo "${args[2]}" | tr -d '%')
            local cur_x=$(echo "$CLIENTS_CACHE" | jq -r ".[] | select(.address == \"$addr\") | .at[0]")

            if [[ "$move_dir" == "l" ]]; then
                if [[ "$cur_x" -gt "$master_threshold" ]]; then
                    log "DEBUG-MOVE" "WS $ws: [L-RULE] $alias is at x=$cur_x. Forcing Left."
                    run_hypr dispatch focuswindow "address:$addr"
                    run_hypr dispatch movewindow l
                    return 
                fi
                
                if [[ -z "${WS_GEOMETRY_LOCKED[$ws]}" ]]; then
                    local tw=$(awk "BEGIN {print int($x_pct * $mon_w / 100)}")
                    log "DEBUG-RESIZE" "WS $ws: Master verified. Resizing $alias to ${tw}px."
                    run_hypr dispatch focuswindow "address:$addr"
                    run_hypr dispatch resizewindowpixel "exact $tw 100%,address:$addr"
                    WS_GEOMETRY_LOCKED[$ws]=1
                fi
                PROCESSED_RULES["$rule_id"]=1
            else
                if [[ "$cur_x" -lt "$master_threshold" ]]; then
                    log "DEBUG-MOVE" "WS $ws: [R-RULE] $alias is at x=$cur_x (Master Spot). Forcing Right."
                    run_hypr dispatch focuswindow "address:$addr"
                    run_hypr dispatch movewindow r
                    return 
                fi
                PROCESSED_RULES["$rule_id"]=1
            fi
            ;;

        "GROUP")
            if [[ -z "${WS_GROUP_LOCKED[$ws]}" ]]; then
                log "ACTION" "WS $ws: Initializing Group (Anchor: $alias)"
                run_hypr dispatch focuswindow "address:$addr"
                run_hypr dispatch togglegroup
                WS_GROUP_LOCKED[$ws]=1
                sleep 0.3
            fi

            local missing=0
            for tail in "${args[@]}"; do
                local t_class="${ALIAS_MAP[$tail]:-$tail}"
                local t_json=$(get_window_data "$t_class" "$ws")
                local t_addr=$(echo "$t_json" | jq -r '.address // empty')
                
                if [[ -n "$t_addr" ]]; then
                    local is_grouped=$(echo "$t_json" | jq -r 'if .grouped != null then (.grouped | length) else 0 end')
                    
                    if [[ "$is_grouped" -eq 0 ]]; then
                        log "ACTION" "WS $ws: Forcing $tail into group"
                        run_hypr dispatch focuswindow "address:$t_addr"
                        sleep 0.1
                        run_hypr dispatch focuswindow "address:$t_addr"
                        
                        for d in l r u d; do run_hypr dispatch moveintogroup "$d"; done
                        sleep 0.2
                        
                        # Fetch fresh data just for this verification
                        local post_json=$(hyprctl clients -j | jq -c ".[] | select(.address == \"$t_addr\")")
                        local post_grouped=$(echo "$post_json" | jq -r 'if .grouped != null then (.grouped | length) else 0 end')
                        
                        if [[ "$post_grouped" -eq 0 ]]; then
                            log "WARN" "WS $ws: $tail escaped the group. Retrying..."
                            missing=$((missing + 1))
                        else
                            log "OK" "WS $ws: $tail successfully locked into group."
                        fi
                    fi
                else
                    missing=$((missing + 1))
                fi
            done
            [[ $missing -eq 0 ]] && PROCESSED_RULES["$rule_id"]=1
            ;;
    esac

    # INSTANT FOCUS
    if [[ -n "${PROCESSED_RULES[$rule_id]}" && "${FOCUS_RULES[$ws]}" == "$alias" ]]; then
        log "FOCUS" "WS $ws: Instant focus applied to $alias"
        run_hypr dispatch focuswindow "address:$addr"
    fi
}

# --- MAIN ENGINE LOOP ---
echo "=== SESSION START: $(date) ===" > "${LOG_FILE}"
start_time=$SECONDS
MAX_ATTEMPTS=3

for (( attempt=1; attempt<=MAX_ATTEMPTS; attempt++ )); do
    log "INFO" "--- RUNNING LAYOUT PASS $attempt ---"
    
    unset PROCESSED_RULES WS_GEOMETRY_LOCKED WS_GROUP_LOCKED
    declare -A PROCESSED_RULES WS_GEOMETRY_LOCKED WS_GROUP_LOCKED

    pass_start=$SECONDS
    while true; do
        all_rules_done=true
        
        # UPDATE CACHE ONCE PER LOOP
        CLIENTS_CACHE=$(hyprctl clients -j)
        MONITORS_CACHE=$(hyprctl monitors -j)
        
        while IFS= read -r line || [[ -n "$line" ]]; do
            [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "$line" ]] && continue
            read -ra args <<< "$line"
            type="${args[0]}"
            [[ ! "$type" =~ ^(RATIO|GROUP)$ ]] && continue
            
            ws="${args[1]}"
            alias="${args[2]}"
            rule_id="${ws}_${type}_${alias}"
            
            if [[ -z "${PROCESSED_RULES[$rule_id]}" ]]; then
                all_rules_done=false
                class="${ALIAS_MAP[$alias]:-$alias}"
                window_json=$(get_window_data "$class" "$ws")
                if [[ -n "$window_json" ]]; then
                    addr=$(echo "$window_json" | jq -r '.address')
                    size=$(echo "$window_json" | jq -r '.size[0]')
                    [[ "$size" -gt 0 ]] && process_rule "$type" "$ws" "$alias" "$addr" "${args[@]:3}"
                fi
            fi
        done < "${CONFIG_FILE}"

        [[ "$all_rules_done" == "true" ]] || [[ $((SECONDS - pass_start)) -gt 60 ]] && break
        sleep 1.5
    done

    break
done

run_hypr dispatch workspace 1
notify-send -u normal -a "Omarchy" "Rice Deployed" "Layout Engine finished"
log "OK" "Engine Offline."
