#!/bin/bash

# --- PATH RESOLUTION ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/layout.conf"
AUTOSTART_FILE="$(realpath "${SCRIPT_DIR}/../autostart.conf")"
LOG_FILE="${SCRIPT_DIR}/layout.log"
PID_FILE="${HOME}/.cache/layout-engine.pid"

# --- CLEAN LOGGING ---
log() {
    local timestamp=$(date +'%H:%M:%S')
    echo "[${timestamp}] [$1] $2" | tee -a "${LOG_FILE}" >&2
}

# --- ENGINE UTILITIES ---
run_hypr() { hyprctl "$@" >> /dev/null 2>&1; }

# === THE FIX: CACHED JSON DATA ===
# Instead of querying the socket every time, we read from a global variable
get_window_data() {
    local class="$1" ws="$2"
    echo "$CLIENTS_CACHE" | jq -c ".[] | select((.class | contains(\"$class\")) and .workspace.id == $ws)" | head -n 1
}

get_window_data_anyws() {
    local class="$1"
    echo "$CLIENTS_CACHE" | jq -c ".[] | select(.class | contains(\"$class\"))" | head -n 1
}

get_grouped_len() {
    local addr="$1"
    echo "$CLIENTS_CACHE" | jq -r ".[] | select(.address == \"$addr\") | (if .grouped != null then (.grouped | length) else 0 end)" | head -n 1
}

ensure_ungrouped() {
    local addr="$1"
    local grouped_len

    grouped_len=$(get_grouped_len "$addr")
    if [[ "$grouped_len" -gt 1 ]]; then
        log "ACTION" "Ungrouping $addr before move"
        run_hypr dispatch focuswindow "address:$addr"
        run_hypr dispatch moveoutofgroup
        sleep 0.1
    fi
}

ensure_tiled() {
    local addr="$1"
    local is_floating

    is_floating=$(echo "$CLIENTS_CACHE" | jq -r ".[] | select(.address == \"$addr\") | .floating" | head -n 1)
    if [[ "$is_floating" == "true" ]]; then
        log "ACTION" "Tiling $addr for grouping"
        run_hypr dispatch focuswindow "address:$addr"
        run_hypr dispatch togglefloating
        sleep 0.1
    fi
}

refresh_clients_cache() {
    CLIENTS_CACHE=$(hyprctl clients -j)
}

try_group_command() {
    local addr="$1"
    shift

    run_hypr dispatch "$@"
    refresh_clients_cache

    local grouped_len
    grouped_len=$(get_grouped_len "$addr")
    [[ "$grouped_len" -gt 0 ]]
}

move_into_group() {
    local addr="$1"
    local dir

    for dir in l r u d; do
        if try_group_command "$addr" movewindow into_or_create_group "$dir"; then return 0; fi
        if try_group_command "$addr" movewindow into_group "$dir"; then return 0; fi
        if try_group_command "$addr" movewindow intogroup "$dir"; then return 0; fi
        if try_group_command "$addr" moveintogroup "$dir"; then return 0; fi
    done

    return 1
}

get_monitor_data() {
    local ws="$1"
    local mon=$(echo "$MONITORS_CACHE" | jq -c ".[] | select(.activeWorkspace.id == $ws)" | head -n 1)
    [[ -z "$mon" ]] && mon=$(echo "$MONITORS_CACHE" | jq -c ".[0]")
    echo "$mon"
}

get_monitor_data_by_addr() {
    local addr="$1"
    local mon_id
    mon_id=$(echo "$CLIENTS_CACHE" | jq -r ".[] | select(.address == \"$addr\") | .monitor" | head -n 1)
    [[ -z "$mon_id" ]] && return
    echo "$MONITORS_CACHE" | jq -c ".[] | select(.id == $mon_id)" | head -n 1
}

get_monitor_layout_width() {
    local mon_json="$1"
    local raw_w=$(echo "$mon_json" | jq -r '.width // 0')
    local scale=$(echo "$mon_json" | jq -r '.scale // 1')
    local reserved_right=$(echo "$mon_json" | jq -r '.reserved[1] // 0')
    local reserved_left=$(echo "$mon_json" | jq -r '.reserved[3] // 0')
    local scaled_w

    scaled_w=$(awk "BEGIN {printf \"%d\", ($raw_w / $scale)}")
    if [[ "$scaled_w" -le 0 ]]; then
        echo "$raw_w"
        return
    fi

    echo $((scaled_w - reserved_left - reserved_right))
}

# --- INITIALIZATION ---
declare -A ALIAS_MAP CMD_MAP WS_MAP FOCUS_RULES

while read -r line; do
    [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "$line" ]] && continue
    read -ra args <<< "$line"
    case "${args[0]}" in
        "APP")
            ALIAS_MAP["${args[1]}"]="${args[2]}"
            CMD_MAP["${args[1]}"]="${args[*]:3}"
            ;;
        "RATIO"|"GROUP"|"SPAWN")
            for app in "${args[@]:2}"; do WS_MAP["$app"]="${args[1]}"; done
            ;;
        "FOCUS")
            if [[ "${args[1]}" =~ ^[0-9]+$ ]]; then
                FOCUS_RULES["${args[1]}"]="${args[2]}"
            else
                al="${args[1]}" # FIX 1: Removed 'local' keyword
                FOCUS_RULES["${WS_MAP[$al]:-1}"]="$al"
            fi
            ;;
    esac
done < "${CONFIG_FILE}"

# === THE MISSING GENERATOR ===
if [[ "$1" == "generate" || "$1" == "--generate" ]]; then
    log "INFO" "Generating $AUTOSTART_FILE..."
    
    # Write custom header
    echo "# Auto-generated by layout-engine for ${USER:-lanusri-}" > "${AUTOSTART_FILE}"
    echo "# Source: ${CONFIG_FILE}" >> "${AUTOSTART_FILE}"
    echo "" >> "${AUTOSTART_FILE}"

    for alias in "${!CMD_MAP[@]}"; do
        ws="${WS_MAP[$alias]}"
        cmd="${CMD_MAP[$alias]}"
        
        # Wrap the command with the uwsm app runner and cache check
        wrapped_cmd="sh -c '[ ! -f \$HOME/.cache/disable_autostart ] && uwsm app -- $cmd'"
        
        if [[ -n "$ws" ]]; then
            echo "exec-once = [workspace $ws silent] $wrapped_cmd" >> "${AUTOSTART_FILE}"
        else
            echo "exec-once = $wrapped_cmd" >> "${AUTOSTART_FILE}"
        fi
    done
    
    # Automatically append the layout engine daemon loop
    echo "exec-once = ${SCRIPT_DIR}/layout.sh --loop" >> "${AUTOSTART_FILE}"
    
    log "OK" "Generation complete. File saved to ${AUTOSTART_FILE}."
    exit 0
fi
# =============================

# --- PID FILE ---
mkdir -p "$(dirname "$PID_FILE")"
echo "$$" > "$PID_FILE"

# --- THE REACTIVE CORE ---
process_rule() {
    local type="$1" ws="$2" alias="$3" addr="$4" args=("${@:5}")
    local rule_id="${ws}_${type}_${alias}"

    [[ -n "${PROCESSED_RULES[$rule_id]}" ]] && return

    local mon_json=$(get_monitor_data_by_addr "$addr")
    [[ -z "$mon_json" ]] && mon_json=$(get_monitor_data "$ws")
    local mon_w=$(get_monitor_layout_width "$mon_json")
    local mon_x=$(echo "$mon_json" | jq -r '.x')
    local master_threshold=$((mon_x + 100))

    case "$type" in
        "SPAWN")
            PROCESSED_RULES["$rule_id"]=1
            ;;
        "RATIO")
            local move_dir="${args[0]}"
            local x_pct=$(echo "${args[2]}" | tr -d '%')
            local ratio_value

            ratio_value=$(awk "BEGIN {printf \"%.2f\", ($x_pct / 100.0)}")
            if [[ -z "$ratio_value" || ! "$ratio_value" =~ ^[0-9.]+$ ]]; then
                log "WARN" "WS $ws: Invalid ratio value '$x_pct' for $alias"
                return
            fi

            # Ensure a dwindle split exists first: moving the window in the requested
            # direction will create the split container. We only do this once per WS.
            if [[ -z "${WS_RATIO_SPLIT_CREATED[$ws]}" ]]; then
                log "DEBUG-RATIO" "WS $ws: Creating dwindle split for $alias by moving $move_dir"
                run_hypr dispatch focuswindow "address:$addr"
                run_hypr dispatch movewindow "$move_dir"
                WS_RATIO_SPLIT_CREATED["$ws"]=1
                return
            fi

            # Resize the rule's own window after the split exists. In dwindle, resizing the
            # target child is stable once the split container has been created.
            local target_pct="$x_pct"
            local tw_px
            tw_px=$(awk "BEGIN {printf \"%d\", ($target_pct/100.0) * $mon_w}")
            log "DEBUG-RATIO" "WS $ws: Resizing $alias at $addr to ${tw_px}px (${target_pct}%)"
            run_hypr dispatch focuswindow "address:$addr"
            run_hypr dispatch resizewindowpixel "exact ${tw_px} 100%,address:$addr"
            sleep 0.2
            PROCESSED_RULES["$rule_id"]=1
            ;;

        "GROUP")
            local moved_tail=0
            for tail in "${args[@]}"; do
                local t_class="${ALIAS_MAP[$tail]:-$tail}"
                local t_json=$(get_window_data "$t_class" "$ws")

                if [[ -z "$t_json" ]]; then
                    local any_json=$(get_window_data_anyws "$t_class")
                    if [[ -n "$any_json" ]]; then
                        local any_addr=$(echo "$any_json" | jq -r '.address // empty')
                        local any_ws=$(echo "$any_json" | jq -r '.workspace.id // empty')

                        if [[ -n "$any_addr" && "$any_ws" != "$ws" && -z "${MOVED_ADDR[$any_addr]}" ]]; then
                            log "ACTION" "WS $ws: Moving $tail from ws $any_ws"
                            ensure_ungrouped "$any_addr"
                            run_hypr dispatch movetoworkspacesilent "$ws,address:$any_addr"
                            MOVED_ADDR["$any_addr"]=1
                            moved_tail=1
                        fi
                    fi
                fi
            done

            [[ "$moved_tail" -eq 1 ]] && return

            if [[ -z "${WS_GROUP_LOCKED[$ws]}" ]]; then
                log "ACTION" "WS $ws: Initializing Group (Anchor: $alias)"
                ensure_tiled "$addr"
                run_hypr dispatch focuswindow "address:$addr"
                run_hypr dispatch togglegroup
                WS_GROUP_LOCKED[$ws]=1
                sleep 0.3
            fi

            local missing=0
            for tail in "${args[@]}"; do
                local t_class="${ALIAS_MAP[$tail]:-$tail}"
                local t_json=$(get_window_data "$t_class" "$ws")
                local t_addr=$(echo "$t_json" | jq -r '.address // empty')
                
                if [[ -n "$t_addr" ]]; then
                    ensure_tiled "$t_addr"
                    local is_grouped=$(echo "$t_json" | jq -r 'if .grouped != null then (.grouped | length) else 0 end')
                    
                    if [[ "$is_grouped" -eq 0 ]]; then
                        log "ACTION" "WS $ws: Forcing $tail into group"
                        run_hypr dispatch focuswindow "address:$t_addr"
                        sleep 0.1
                        run_hypr dispatch focuswindow "address:$t_addr"

                        local moved_ok=0
                        if move_into_group "$t_addr"; then
                            moved_ok=1
                        fi

                        # Fetch fresh data just for this verification
                        local post_json=$(hyprctl clients -j | jq -c ".[] | select(.address == \"$t_addr\")")
                        local post_grouped=$(echo "$post_json" | jq -r 'if .grouped != null then (.grouped | length) else 0 end')
                        
                        if [[ "$post_grouped" -eq 0 || "$moved_ok" -eq 0 ]]; then
                            log "WARN" "WS $ws: $tail escaped the group. Retrying..."
                            missing=$((missing + 1))
                        else
                            log "OK" "WS $ws: $tail successfully locked into group."
                        fi
                    fi
                else
                    missing=$((missing + 1))
                fi
            done
            [[ $missing -eq 0 ]] && PROCESSED_RULES["$rule_id"]=1
            ;;
    esac

    # INSTANT FOCUS
    if [[ -n "${PROCESSED_RULES[$rule_id]}" && "${FOCUS_RULES[$ws]}" == "$alias" ]]; then
        log "FOCUS" "WS $ws: Instant focus applied to $alias"
        run_hypr dispatch focuswindow "address:$addr"
    fi
}

# --- MAIN ENGINE LOOP ---
echo "=== SESSION START: $(date) ===" > "${LOG_FILE}"
start_time=$SECONDS
MAX_ATTEMPTS=3

for (( attempt=1; attempt<=MAX_ATTEMPTS; attempt++ )); do
    log "INFO" "--- RUNNING LAYOUT PASS $attempt ---"
    
    unset PROCESSED_RULES WS_GEOMETRY_LOCKED WS_GROUP_LOCKED MOVED_ADDR WS_RATIO_SPLIT_CREATED
    declare -A PROCESSED_RULES WS_GEOMETRY_LOCKED WS_GROUP_LOCKED MOVED_ADDR WS_RATIO_SPLIT_CREATED

    pass_start=$SECONDS
    while true; do
        all_rules_done=true
        
        # UPDATE CACHE ONCE PER LOOP
        CLIENTS_CACHE=$(hyprctl clients -j)
        MONITORS_CACHE=$(hyprctl monitors -j)
        
        while IFS= read -r line || [[ -n "$line" ]]; do
            [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "$line" ]] && continue
            read -ra args <<< "$line"
            type="${args[0]}"
            [[ ! "$type" =~ ^(RATIO|GROUP|SPAWN)$ ]] && continue
            
            ws="${args[1]}"
            alias="${args[2]}"
            rule_id="${ws}_${type}_${alias}"
            
            if [[ -z "${PROCESSED_RULES[$rule_id]}" ]]; then
                all_rules_done=false
                class="${ALIAS_MAP[$alias]:-$alias}"
                window_json=$(get_window_data "$class" "$ws")

                if [[ -z "$window_json" ]]; then
                    any_json=$(get_window_data_anyws "$class")
                    if [[ -n "$any_json" ]]; then
                        any_addr=$(echo "$any_json" | jq -r '.address')
                        any_ws=$(echo "$any_json" | jq -r '.workspace.id')

                        if [[ "$any_ws" != "$ws" && -z "${MOVED_ADDR[$any_addr]}" ]]; then
                            log "ACTION" "WS $ws: Moving $alias from ws $any_ws"
                            ensure_ungrouped "$any_addr"
                            run_hypr dispatch movetoworkspacesilent "$ws,address:$any_addr"
                            MOVED_ADDR["$any_addr"]=1
                            continue
                        fi
                    fi
                fi

                if [[ -n "$window_json" ]]; then
                    addr=$(echo "$window_json" | jq -r '.address')
                    size=$(echo "$window_json" | jq -r '.size[0]')
                    [[ "$size" -gt 0 ]] && process_rule "$type" "$ws" "$alias" "$addr" "${args[@]:3}"
                fi
            fi
        done < "${CONFIG_FILE}"

        [[ "$all_rules_done" == "true" ]] || [[ $((SECONDS - pass_start)) -gt 60 ]] && break
        sleep 1.5
    done

    break
done

run_hypr dispatch workspace 1
notify-send -u normal -a "Omarchy" "Rice Deployed" "Layout Engine finished"
log "OK" "Engine Offline."
