# ==============================================================================
# APP DEFINITIONS
# hyprctl clients -j | jq -r '.[] | "\(.class) -> \(.title)"'
# ==============================================================================
APP discord  vesktop                              vesktop
#APP spotify  Spotify                              spotify
APP beeper   Beeper                               beeper
APP todoist  chrome-app.todoist.com__app-Default  chromium --app=https://app.todoist.com/app --user-data-dir="/home/l4n1skyy/.config/todoist-app"
APP calendar chrome-calendar.google.com__-Default omarchy-launch-webapp https://calendar.google.com
APP obsidian obsidian                             obsidian
#APP nvim     org.omarchy.nvim                     alacritty --class org.omarchy.nvim -e nvim
#APP cbonsai  cbonsai-term                         alacritty --class cbonsai-term -e cbonsai -i -l
APP zen      zen                                  zen-browser
#APP pomo     pomoru-term                          /home/l4n1skyy/.local/bin/pomoru-autostart

# ==============================================================================
# LAYOUT RULES
# GROUP <workspace> <alias>
# SPAWN <workspace> <alias>
# RATIO <workspace> <alias> <directions> <y_percent> <x_percent>
# FOCUS <workspace> <alias>
# ==============================================================================

# --- WORKSPACE 10: SOCIAL ---
GROUP 10 beeper discord
FOCUS 10 beeper

# --- WORKSPACE 9: NOTETAKING ---
SPAWN 9 obsidian
FOCUS 9 obsidian

# --- WORKSPACE 8: PRODUCTIVITY ---
RATIO 8 todoist     l   100%    25%
RATIO 8 calendar    r   100%    75%

# --- WORKSPACE 1: THE DASHBOARD ---
SPAWN 1 zen
FOCUS 1 zen
