-- Auto-generated by layout-engine for l4n1skyy
-- Source: /home/l4n1skyy/.local/bin/hypr/layout.conf

local TRACE_FILE = "/home/l4n1skyy/.cache/hypr-autostart.log"
local function trace(message)
    local file = io.open(TRACE_FILE, "a")
    if file then
        file:write(os.date("!%Y-%m-%dT%H:%M:%SZ ") .. message .. "\n")
        file:close()
    end
end

local function launch_if_enabled(command)
    local disable_path = (os.getenv("HOME") or "/home/l4n1skyy") .. "/.cache/disable_autostart"
    local file = io.open(disable_path, "r")
    if file then
        file:close()
        return
    end

    hl.exec_cmd(command)
end

trace("autostart.lua loaded")
hl.on("hyprland.start", function()
  trace("hyprland.start fired")
  hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  trace("launch requested: kanshi")
  hl.exec_cmd(o.launch("kanshi"))
  trace("launch requested: discord -> vesktop")
  launch_if_enabled(o.launch("vesktop"))
  trace("launch requested: beeper -> beeper")
  launch_if_enabled(o.launch("beeper"))
  trace("launch requested: todoist -> chromium --app=https://app.todoist.com/app --user-data-dir=\"/home/l4n1skyy/.config/todoist-app\"")
  launch_if_enabled(o.launch("chromium --app=https://app.todoist.com/app --user-data-dir=\"/home/l4n1skyy/.config/todoist-app\""))
  trace("launch requested: calendar -> omarchy-launch-webapp https://calendar.google.com")
  launch_if_enabled(o.launch("omarchy-launch-webapp https://calendar.google.com"))
  trace("launch requested: obsidian -> obsidian")
  launch_if_enabled(o.launch("obsidian"))
  trace("launch requested: zen -> zen-browser")
  launch_if_enabled(o.launch("zen-browser"))
  trace("layout engine requested")
  hl.exec_cmd("/home/l4n1skyy/.local/bin/hypr/layout.sh --loop")
end)
