exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- obsidian'
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- beeper'
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- vesktop'
