# Workspace 1
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- alacritty --class cbonsai-term -e cbonsai -li'
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- alacritty --class org.omarchy.nvim -e nvim'

# Workspace 2
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- zen-browser'

# Workspace 9
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- obsidian'
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- chromium --app=https://app.todoist.com/app --user-data-dir="/home/l4n1skyy/.config/todoist-app"'
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- omarchy-launch-webapp https://calendar.google.com'

# Workspace 10
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- beeper'
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- vesktop'
exec-once = sh -c '[ ! -f $HOME/.cache/disable_autostart ] && uwsm app -- spotify'

# The Layout Script
exec-once = ~/.config/hypr/layout.sh
