
# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

exec-once = kanshi

windowrule {
    name = steam-client-maximize
    match:class = ^steam$
    match:initial_class = ^steam$
    maximize = on
}

### AUTOSTART
# --- Workspace 1: Triple-Stack Dev ---
windowrule {
    name = dev-layout
    match:class = ^(org\.omarchy\.nvim|cbonsai-term|timr-term)$
    workspace = 1
}

# Workspace 2: Browser
windowrule {
    name = ws2
    match:class = ^zen$
    workspace = 2
}

# Workspace 9: Productivity
windowrule {
    name = ws9
    match:class = ^(obsidian|chrome-app\.todoist\.com__app-Default|chrome-calendar\.google\.com__-Default)$
    workspace = 9
}

# Workspace 10: Social
windowrule {
    name = ws10
    match:class = ^(Spotify|vesktop|BeeperTexts)$
    workspace = 10
}
