# ~/.config/hypr/hyprlock.conf
general {
    fail_timeout = 1000
    ignore_empty_input = true
    no_fade_in = true
    no_fade_out = true
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = inputFieldColors, 1, 3, linear
    animation = inputFieldDots, 1, 3, linear
}

background {
    monitor =
    color = rgb(24, 25, 26)
}

input-field {
    monitor =
    size = 400, 50
    outline_thickness = 0

    outer_color = rgb(24, 25, 26)
    inner_color = rgb(24, 25, 26)
    check_color = rgb(24, 25, 26)
    fail_color = rgb(24, 25, 26)

    font_color = rgb(255, 255, 255)
    dots_size = 0.48
    dots_spacing = 0.15
    dots_center = true
    dots_text_format = .

    placeholder_text = <span font_family="CozetteVector" font_size="18pt" foreground="white">shoo, go away &gt;:(</span>
    fail_text = <span font_family="CozetteVector" font_size="18pt" foreground="red">YOU SHALL NOT PASS D:&lt;</span>

    fade_on_empty = false
    hide_input = false

    position = 0, 0
    halign = center
    valign = center
}
