# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 3
    gaps_out = 7
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling
    col.active_border = rgba(b4befeaa) rgba(f5c2e7aa) 45deg
    col.inactive_border = rgba(1e1e2e55)
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    bezier = wind, 0.05, 0.9, 0.1, 1
    bezier = winIn, 0.1, 1.05, 0.1, 1
    bezier = winOut, 0.3, -0.3, 0.1, 1
    bezier = liner, 1, 1, 1, 1
    
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

group {
    groupbar {
        font_family = CozetteVector
        font_size = 0
        rounding = 10
        height = 5
        
        col.active = rgba(463b55ff)   # Solid muted purple matching the Waybar
        col.inactive = rgba(2d253b88) # A darker, solid version for inactive tabs
    }
}
